# Generated by Django 4.2.5 on 2023-09-04 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autenticaciones',
            fields=[
                ('idautenticacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=50)),
                ('tipoUsuario', models.CharField(max_length=50)),
                ('idautenticacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.autenticaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('idrating', models.BigAutoField(primary_key=True, serialize=False)),
                ('calificaciones', models.CharField(max_length=100)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('idinmueble', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('tipoInmueble', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=150)),
                ('precio', models.FloatField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=50)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('idcita', models.BigAutoField(primary_key=True, serialize=False)),
                ('horaCita', models.DateTimeField()),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AsesorFk', to='usuarios.usuario')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioFk', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Aprobaciones',
            fields=[
                ('idaprobaciones', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('copiaCedula', models.CharField(max_length=50)),
                ('certificadoLibertad', models.CharField(max_length=50)),
                ('cedula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('idinmueble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.inmuebles')),
            ],
        ),
    ]
